features:
  prevent-enderpearl-chunkloading: false
  chunk-tick-distance-affects-random-ticks: false
  prevent-moving-into-unloaded-chunks: false
  autosave-interval-seconds: 300
  xp-merge-fraction: 40
  xp-merge-radius: 0.5
  item-merge-radius: 0.5
  lobotomize-villagers:
    enabled: false
    tick-interval: 20

dynamic:
  enabled: false
  target-mspt: 35
  default-values:
    MOBCAP_PERCENTAGE: 100
    CHUNK_TICK_DISTANCE: 10
  dynamic-settings:
    - setting: 'CHUNK_TICK_DISTANCE'
      max: 10
      min: 6
      increment: 1
      interval: 15
    - setting: 'MOBCAP_PERCENTAGE'
      max: 100
      min: 50
      increment: 10
      interval: 15
    - setting: 'SIMULATION_DISTANCE'
      max: 10
      min: 6
      increment: 1
      interval: 15
    - setting: 'CHUNK_TICK_DISTANCE'
      max: 6
      min: 2
      increment: 1
      interval: 15
    - setting: 'MOBCAP_PERCENTAGE'
      max: 50
      min: 30
      increment: 10
      interval: 15
    - setting: 'SIMULATION_DISTANCE'
      max: 6
      min: 2
      increment: 1
      interval: 15
    - setting: 'VIEW_DISTANCE'
      max: 10
      min: 5
      increment: 1
      interval: 150

breeding-cap:
  enabled: false
  villagers:
    limit: 32
    range: 64
    unlimited-height: false
  animals:
    limit: 32
    range: 64
    unlimited-height: false

mob-spawning:
  zombie-reinforcements:
    enforce-mobcap: false
    additional-capacity: 32
  nether-portal-randomticks:
    enforce-mobcap: false
    additional-capacity: 32
  monster-spawners:
    enforce-mobcap: false
    additional-capacity: 32
  infested:
    enforce-mobcap: false
    additional-capacity: 32
  categories:
    - category: 'MONSTER'
      mobcap: 140
      spawn-interval: 1
    - category: 'CREATURE'
      mobcap: 10
      spawn-interval: 400
    - category: 'AMBIENT'
      mobcap: 15
      spawn-interval: 1
    - category: 'AXOLOTLS'
      mobcap: 5
      spawn-interval: 1
    - category: 'UNDERGROUND_WATER_CREATURE'
      mobcap: 5
      spawn-interval: 1
    - category: 'WATER_CREATURE'
      mobcap: 5
      spawn-interval: 1
    - category: 'WATER_AMBIENT'
      mobcap: 20
      spawn-interval: 1

commands:
  status-enabled: true
  mobcaps-enabled: true
  colors:
    primary: 'dark_aqua'
    secondary: 'green'
    tertiary: 'aqua'

activation-range:
  enabled: false
  tick-new-entities: true
  use-vertical-range: false
  skip-non-immune: false
  villager-tick-panic: true
  villager-work-immunity-after: 20
  villager-work-immunity-for: 20
  excluded-entity-types:
    - 'minecraft:ghast'
    - 'minecraft:hopper_minecart'
    - 'minecraft:warden'
  default-activation-type:
    activation-range: 16
    tick-interval: 20
    wakeup-interval: -1
    extra-height-up: false
    extra-height-down: false
  custom-activation-types:
    - name: 'raider'
      activation-range: 48
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'typeof:raider'
    - name: 'water'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 60
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:water_animal'
    - name: 'villager'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 30
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:villager'
    - name: 'zombie'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'minecraft:zombie'
        - 'minecraft:husk'
    - name: 'monster-below'
      activation-range: 32
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: true
      entity-matcher:
        - 'minecraft:creeper'
        - 'minecraft:slime'
        - 'minecraft:magma_cube'
        - 'minecraft:hoglin'
    - name: 'flying-monster'
      activation-range: 48
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'minecraft:ghast'
        - 'minecraft:phantom'
    - name: 'monster'
      activation-range: 32
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'typeof:monster'
    - name: 'animal'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 60
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:animal'
        - 'typeof:ambient'
    - name: 'creature'
      activation-range: 24
      tick-interval: 20
      wakeup-interval: 30
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:mob'
