services:
  reverse-proxy:
    image: traefik:v2.8
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/etc/traefik/acme.json
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml:ro
    restart: always
    networks:
      - web

networks:
  web:
    external: true

