[http.middlewares.simpleAuth.basicAuth]
  usersfile = "/etc/traefik/usersfile"

[http.routers.api]
  rule = "Host(`traefik.timkley.dev`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[http.serversTransports.insecureskipverify]
  insecureSkipVerify = true
