[core]
  strictTLSOptions = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.transport]
      [entryPoints.websecure.transport.respondingTimeouts]
        readTimeout = "600s"
        idleTimeout = "600s"
    [entryPoints.websecure.http]
      underscoreHeadersStrategy = "delete"
    [entryPoints.websecure.http.tls]
      certResolver = "lets-encrypt"

  [entryPoints.health]
    address = ":8082"

[api]
  dashboard = true

[ping]
  entryPoint = "health"

[accessLog]
  format = "json"
  [accessLog.filters]
    statusCodes = ["400-599"]
    retryAttempts = true
    minDuration = "100ms"
  [accessLog.fields.headers]
    defaultMode = "drop"

[certificatesResolvers.lets-encrypt.acme]
  email = "timkley@gmail.com"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.lets-encrypt.acme.dnsChallenge]
    provider = "cloudflare"
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
    [certificatesResolvers.lets-encrypt.acme.dnsChallenge.propagation]
      delayBeforeChecks = "10s"

[providers.docker]
  watch = true
  network = "web"
  exposedByDefault = false

[providers.file]
  directory = "/etc/traefik/dynamic/"
  watch = true
