services:
  app:
    image: typesense/typesense:28.0
    restart: unless-stopped
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=${API_KEY} --enable-cors'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.timkley.dev`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8108"
    networks:
      - web

networks:
  web:
    external: true