services:
  mongo:
    image: mongo:3.6
    container_name: unifi_mongo
    networks:
      - unifi
    restart: always
    volumes:
      - db:/data/db
      - dbcfg:/data/configdb
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: unifi_controller
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
      - web
    restart: always
    volumes:
      - dir:/unifi
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
      - run:/var/run/unifi
      # Mount local folder for backups and autobackups
      - ./backup:/unifi/data/backup
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.entrypoints=web"
      - "traefik.http.routers.unifi.rule=Host(`unifi.timkley.dev`)"
      - "traefik.http.middlewares.unifi-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.unifi.middlewares=unifi-https-redirect"
      - "traefik.http.routers.unifi-secure.entrypoints=websecure"
      - "traefik.http.routers.unifi-secure.rule=Host(`unifi.timkley.dev`)"
      - "traefik.http.routers.unifi-secure.tls=true"
      - "traefik.http.routers.unifi-secure.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.unifi-secure.service=unifi"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      - "traefik.http.services.unifi.loadbalancer.serverstransport=insecureskipverify@file"
      - "traefik.http.middlewares.unifi-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.unifi-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.unifi-headers.headers.customrequestheaders.X-Real-IP={{ .RemoteAddr }}"
      - "traefik.http.routers.unifi-secure.middlewares=unifi-headers"
      - "traefik.http.middlewares.unifi-compress.compress=true"
      - "traefik.http.routers.unifi-secure.middlewares=unifi-headers,unifi-compress"
      - "traefik.docker.network=web"
  logs:
    image: bash
    container_name: unifi_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - log:/unifi/log

volumes:
  db:
  dbcfg:
  data:
  log:
  cert:
  init:
  dir:
  run:

networks:
  unifi:
  web:
    external: true
