services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    restart: "unless-stopped"
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.6"
      ENABLE_STATUS: "true"
      TYPE: "FABRIC"
      MEMORY: "3072M"
      MAX_PLAYERS: "5"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      TZ: "Europe/Berlin"
      DIFFICULTY: "2"
      LEVEL: "${WORLD}"
      OPS: |-
        timkley
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        timkley
        PitBull2709
        paulipantheri
        timkley1
      MODRINTH_PROJECTS: |-
        armor-poser
        lithium
        audioplayer
        ferrite-core
        inventory-totem
        just-mob-heads
        shulker-drops-two
        waystones
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      SPAWN_PROTECTION: "0"
      PLUGINS: |-
        https://modrinth.com/plugin/simple-voice-chat
    volumes:
      - "./data:/data"

  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      RCON_PASSWORD: "${RCON_PASSWORD}"
      TZ: "Europe/Berlin"
    volumes:
      - "./data:/data:ro"
      - "./backups:/backups"
    labels:
      - "traefik.enable=false"
