services:
  mc:
    image: itzg/minecraft-server:2026.9.2@sha256:de5d1b1a83eba576f6c8a688fac2a3523ce457724cdebc8ea48d7818b74cdf6e
    tty: true
    stdin_open: true
    restart: "unless-stopped"
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "26.2"
      ENABLE_STATUS: "true"
      TYPE: "FABRIC"
      INIT_MEMORY: "512M"
      MAX_MEMORY: "3072M"
      MAX_PLAYERS: "5"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      TZ: "Europe/Berlin"
      DIFFICULTY: "hard"
      SIMULATION_DISTANCE: "10"
      LEVEL: "${WORLD}"
      OPS: |-
        timkley
        paulipantheri
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        timkley
        PitBull2709
        paulipantheri
        timkley1
        Kontheria
      MODRINTH_PROJECTS: |-
        armor-poser
        lithium
        audioplayer
        ferrite-core
        inventory-totem
        just-mob-heads
        shulker-drops-two
        # waystones
        glitchcore
        terrablender
        servercore
        spark
        simple-voice-chat
        xaeros-world-map
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      SPAWN_PROTECTION: "0"
    volumes:
      - "./data:/data"
      - "./servercore:/data/config/servercore"

  backups:
    image: itzg/mc-backup:2026.9.3@sha256:3ff6a1e8fa15ca4e4440b118676cf58c611a4079d4da8fe792b04a9a13619f16
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      RCON_PASSWORD: "${RCON_PASSWORD}"
      TZ: "Europe/Berlin"
    volumes:
      - "./data:/data:ro"
      - "./backups:/backups"
    labels:
      - "traefik.enable=false"
