services:
  app:
    restart: unless-stopped
    image: vabene1111/recipes:2.6.15@sha256:2e759dd1478a2ed119ee474e28522079fb1cfa50b3fd25cba89f6b9a67abad72
    env_file:
      - ./.env
    environment:
      GUNICORN_WORKERS: "1"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header='Host: ${COMPOSE_PROJECT_NAME}.timkley.dev' http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
      - ./database/db.sqlite3:/opt/recipes/db.sqlite3
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.timkley.dev`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=lets-encrypt"
    networks:
      - web
      - default

  db:
    restart: unless-stopped
    image: postgres:16.15-alpine@sha256:3c5c8892d184f738f4fe282d14ddaa613a38f00f4189d2d94725ebe6f2909ddb
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

networks:
  web:
    external: true

volumes:
  staticfiles:
